# Streamlit Cloud Secrets Configuration
# Copy this content to your Streamlit Cloud app secrets section

# Required: Mistral AI API Key for question generation and evaluation
MISTRAL_API_KEY = "your_actual_mistral_api_key_here"

# Optional: Debug mode (set to "false" for production)
DEBUG = "false"

# Optional: Custom Mistral API endpoint
MISTRAL_BASE_URL = "https://api.mistral.ai/v1"

# Instructions:
# 1. Go to your Streamlit Cloud app settings
# 2. Navigate to "Secrets" section
# 3. Copy the above configuration (without this comment block)
# 4. Replace "your_actual_mistral_api_key_here" with your real API key
# 5. Save the secrets configuration
